name: Manual Deploy to Scalingo

on:
  workflow_dispatch:
    inputs:
      scalingo_token:
        description: 'Scalingo API Token'
        required: true
        type: string
      app_name:
        description: 'Scalingo Application Name'
        required: true
        type: string
      branch:
        description: 'Branch to deploy'
        required: false
        default: 'main'
        type: string

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Scalingo CLI
        uses: scalingo-community/setup-scalingo@v0.1.1
        with:
          region: 'osc-fr1'
          api_token: ${{ inputs.scalingo_token }}
          app_name: ${{ inputs.app_name }}

      - name: Deploy to Scalingo
        run: |
          git push scalingo ${{ inputs.branch }}:master
